name: Run Unit Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install jest
        run: npm install jest --save-dev

      - name: Run unit tests
        run: npm test
